### PR TITLE
MAX31855/MAX6675 sensors driver support up to 6

### LINKED ISSUE #9329: Support to Configure Multiple MAX6675 Thermocouple Sensors
### PROBLEM DESCRIPTION

I cannot see the outputs of two max 6675 thermocouple sensors.  I see the outputs of one at a time only.  I’ve added each thermocouple sensor CS on different Pins.  

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): _____
- [x] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [x] Self-compiled
    - [ ] IDE / Compiler used: _____
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:


```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

### PR DESCRIPTION
**Pull request by ltpop**
## Description:

**Related issue (if applicable):** fixes #9329

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with Tasmota core ESP32 V.2.0.14
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

File: tasmota/include/tasmota_template_legacy.h [hunk 1]
```diff
@@ -144,7 +144,12 @@ enum LegacyUserSelectablePins {
   GPI8_RF_SENSOR,      // Rf receiver with sensor decoding
   GPI8_AZ_TXD,         // AZ-Instrument 7798 Serial interface
   GPI8_AZ_RXD,         // AZ-Instrument 7798 Serial interface
-  GPI8_MAX31855CS,     // MAX31855 Serial interface
+  GPI8_MAX31855CS1,    // MAX31855 Serial interface
```
Comment (arendst) [inline tasmota/include/tasmota_template_legacy.h:147]: Do NOT MAKE ANY CHANGES in this file.

File: tasmota/tasmota_xsns_sensor/xsns_39_max31855.ino [hunk 2]
```diff
@@ -114,54 +124,67 @@ float MAX31855_GetReferenceTemperature(int32_t RawData) {
...
+        sprintf(sensor_name, "%s%c%d",sensor_name_text, IndexSeparator(), i);
+      }
+
+      if (Json) {
+        ResponseAppend_P(PSTR(",\"%s\":{\"" D_JSON_TEMPERATURE "\":%*_f,\"" D_JSON_REFERENCETEMPERATURE "\":%*_f,\"" D_JSON_ERROR "\":%d}"), \
+          sensor_name,
+          Settings->flag2.temperature_resolution, &MAX31855_Result[i].ProbeTemperature,
+          Settings->flag2.temperature_resolution, &MAX31855_Result[i].ReferenceTemperature,
+          MAX31855_Result[i].ErrorCode);
 #ifdef USE_DOMOTICZ
```
Comment (arendst) [inline tasmota/tasmota_xsns_sensor/xsns_39_max31855.ino:172]: Do not update both Domoticz and KNX with different sensors. See xsns_47_max31865 how to solve
